### ISSUE TITLE
Rationalize duplicated build artifacts: 77+MB -> 7 MB

### ISSUE THREAD

**Issue by taqtiqa-mark** [zombiezen/redo-rs#23] opened 2022-01-28 06:25 UTC
Currently the (linux) build artifacts are approx 77.MB.  

It appears this can be improved (substantially?) by building a single binary and providing symlinks rather than binary blobs: `redo`, `redo-ifchange`, etc

I've used clap a little, but am not a guru.

However, it should be possible to branch on the content of `argv[0]`. Hence, rather than have separate binaries, a symlink such as `redo-ifchange` to `redo` should be possible, and only one binary blob need be created?

**Comment by zombiezen** [comment] 2022-01-28 15:45
Dude, stop. You are creating a huge amount of noise on a repository I made in my spare time for fun to learn Rust.

This is a duplicate of #1, which I already addressed. The new release operates exactly as you describe, with symlinks.

**Closed** 2022-01-28 15:46 UTC

**Comment by taqtiqa-mark** [comment] 2022-01-30 01:36
> This is a duplicate of #1

Apologies I overlooked that.
